/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_kth_maandree_noxutil_Recaps */

#ifndef _Included_se_kth_maandree_noxutil_Recaps
#define _Included_se_kth_maandree_noxutil_Recaps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_kth_maandree_noxutil_Recaps
 * Method:    createPTS
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_se_kth_maandree_noxutil_Recaps_createPTS
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
